name: Run tests
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Install dependencies
        run: mvn install

      - name: Run tests and save results
        run: |
          mvn test | tee test_results.txt
          if grep -q "Tests run: 0, Failures: 0, Errors: 0, Skipped: 0" test_results.txt; then
            echo "Тесты успешно пройдены. Все ок."
          else
            echo "Тесты не пройдены. Вот список упавших тестов и ошибок:"
            cat test_results.txt
          fi

      - name: Send Telegram notification and report if failure
        if: failure()
        run: |
          curl -F chat_id=${{ secrets.TELEGRAM_CHAT_ID }} -F document=@test_results.txt https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendDocument
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} -d text="Tests failed. Full report has been sent."
