name: Run tests
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Install dependencies
        run: mvn install

      - name: Run tests
        run: |
          mvn test | tee test_results.txt
          if grep -q "Tests run: 0, Failures: 0, Errors: 0, Skipped: 0" test_results.txt; then
            echo "Тесты успешно пройдены. Все ок."
          else
            echo "Тесты не пройдены. Вот список упавших тестов:"
            grep -A1 "Failed tests:" test_results.txt | tail -n +2
          fi

      - name: Send Telegram notification
        if: failure()
        run: |
          echo "Тесты не пройдены. Вот список упавших тестов:" > telegram_message.txt
          grep -A1 "Failed tests:" test_results.txt | tail -n +2 >> telegram_message.txt
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} -d text="$(cat telegram_message.txt)"
