name: Run Tests on Commit

on:
  push:
    branches:
      - master 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Run tests
      run: |
        ./gradlew test 
