name: Run tests
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Install dependencies
        run: mvn install

      - name: Run tests
        id: test
        run: | 
          set -e
          mvn test || (echo "::set-output name=tests_failed::true" && exit 0)

      - name: Notify on success
        if: ${{ steps.test.outcome == 'success' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: все ок

      - name: Notify on failure
        if: ${{ steps.test.outcome == 'failure' }}
        run: |
          echo "Тесты не пройдены. Подробности:"
          echo "${{ steps.test.outputs.tests_failed }}"
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: "Тесты не пройдены. Подробности см. в логах Actions"
